# Generated by Django 3.1.7 on 2021-05-06 09:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('deals', '0002_file_test'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='test',
            name='total',
        ),
    ]
